S = group
group = <'{'> (group-item, (<','> group-item)*)? <'}'>
<group-item> = group | garbage
garbage = <'<'> (garbage-chars | garbage-cancel)* <'>'>
<garbage-chars> = #'[^>!]'
<garbage-cancel> = '!' #'.'